firstname = input("please enter your first name:")
lastname = input("please enter your last name:")
print("hello " + firstname + " " + lastname)
print("hello {} {}".format(firstname, lastname)) 
print("hello {0} {1}".format(firstname, lastname)) 
print("hello {1} {0}".format(firstname, lastname)) 
print(f"hello {firstname} {lastname}")
print("hello {1} {0} {2}".format(firstname, lastname, "test")) 
output = "hello {1} {0} {2}".format(firstname, lastname, "test")
print("output is " + output)
print("my out is " + output)
print("firstname is " + firstname)
firstname = "andrew"
print("firstname is " + firstname)
firstname = "a"
print("firstname is " + firstname)
output = "hello {1} {0} {2}".format(firstname, lastname, "test")
print("my 2n out is " + output)
